### ISSUE TITLE
how does performance change with the length of the audio?

### ISSUE THREAD

**Issue by StanSilas** [lucko515/speech-recognition-neural-network#1]
Is this method more suited to shorter bursts of audio or can it be employed for transcription on audio of longer duration say 30-40 minutes? 
i.e is there a considerable decay in performance when applied to longer audio files?

**Comment by lucko515** [comment]
Hmm good point. I haven't had chance to test it out on that long audio. The most samples in the dataset are 1 max 2 sentences.
